experiment_name: xlx_clean_roi_512_finetune
output_root: ./runs
data:
  root: ./data/xlx_clean_roi_512
model:
  in_channels: 3
  out_channels: 3
  downscale_factor: 4
  rep_scale: 4
  only_train_y: true
  pretrain_path: /mnt/d/fudan/prefilter_clean/weights/iccv_yan_2025_fp32.pth
  strict_load: true
train:
  seed: 123
  device: cuda
  batch_size: 16
  val_batch_size: 1
  num_workers: 4
  crop_size: 224
  hflip: true
  lr: 1.0e-05
  min_lr: 1.0e-06
  weight_decay: 1.0e-06
  total_iter: 12000
  warmup_iter: 500
  mixed_precision: false
  resume: auto
  fidelity_loss:
    enabled: true
    loss_weight: 1.0
    eps: 1.0e-12
    roi_weight: 20.0
    non_roi_weight: 1.0
  perceptual_loss:
    enabled: true
    loss_weight: 0.16
    data_range: 1.0
    win_size: 11
    win_sigma: 1.5
  scheduler:
    T_max: 12000
    eta_min: 1.0e-06
logger:
  print_freq: 200
  val_freq: 500
  save_latest_freq: 500
  save_checkpoint_freq: 2000
